### ISSUE TITLE
Canidesk > Manage > edit mailbox > cross icon does not display and double bracket sign show. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#103]
**What's not working **
Canidesk > Manage > edit mailbox > cross icon does not display and double bracket sign show. 
![Screenshot 2023-06-20 162514](https://github.com/canaris-in/canidesk/assets/114991909/c352918a-1f60-4677-a9b8-1781fa679b71)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (114)](https://github.com/canaris-in/canidesk/assets/103345777/03b3fd71-7d42-4f48-b285-e5674768a220)

**Comment by lalit510** [comment]
it's working.
