### ISSUE TITLE
Canidesk > Manage > customers > search not properly working, searched customer name removes search field, but name show permanently

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#107]
**What's not working **
Canidesk > Manage > customers > search not properly working, searched customer name removes search field, but name show permanently.
![Screenshot 2023-06-21 103548](https://github.com/canaris-in/canidesk/assets/114991909/5ca27b74-c747-489c-94d8-f2d170f49e7c)

**Comment by rajeshcanaris** [comment]
it is working
![Screenshot from 2023-06-28 23-28-22](https://github.com/canaris-in/canidesk/assets/133959091/7b9be37e-b580-4290-8f17-e9696592c994)
![Screenshot from 2023-06-28 23-28-08](https://github.com/canaris-in/canidesk/assets/133959091/1da319b0-4e9e-47b8-9347-0086b53089af)

**Comment by lalit510** [comment]
it's not working now

**Comment by rajeshcanaris** [comment]
this is working now

**Comment by lalit510** [comment]
it's working now
