### ISSUE TITLE
Canidesk > manage > customers > search field not properly display in dark mode. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#108]
**What's not working **
Canidesk > manage > customers > search field not properly display in dark mode. 
![Screenshot 2023-06-21 103721](https://github.com/canaris-in/canidesk/assets/114991909/40654105-8b14-43b2-bf86-76407d21b76b)

**Comment by pravinpimpale** [comment]
It is done 
![Screenshot (115)](https://github.com/canaris-in/canidesk/assets/103345777/b00eff72-fbb8-46cf-a3f6-2d2ac83497b3)

**Comment by lalit510** [comment]
it's working
