### ISSUE TITLE
Canidesk > Reports > settings > Schedule field not working 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#109]
**What's not working **
Cani desk > Reports > settings > Schedule field not working.
![Screenshot 2023-06-21 120440](https://github.com/canaris-in/canidesk/assets/114991909/3c038c2b-3092-4ddb-b4db-a9ee30f92c4c)

**Comment by pravinpimpale** [comment]
It is fiexed by rajesh

**Comment by lalit510** [comment]
it's working now
