### ISSUE TITLE
Cani-desk > Reports > Escaled field and Type text between add some space. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#113]
**What's not working **
Cani-desk > Reports > Escaled field and Type text between add some space. 
![Screenshot 2023-06-21 125300](https://github.com/canaris-in/canidesk/assets/114991909/b5671ade-2f7d-4de0-961d-5173a73dcd87)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (120)](https://github.com/canaris-in/canidesk/assets/103345777/c34ca382-c6d8-4a2a-93ee-892c7371823a)

**Comment by lalit510** [comment]
it's working.
