### ISSUE TITLE
Cani desk > manage > mailbox > Connection Settings > Except of "free scout " text change Cani-desk   

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#114]
**What's not working **
Cani desk > manage > mailbox > Connection Settings > Except of "free scout " text change Cani-desk   
![Screenshot 2023-06-21 123334](https://github.com/canaris-in/canidesk/assets/114991909/dce7ccf3-c5bf-4e4c-9bab-6cfefb6f1197)

**Comment by pravinpimpale** [comment]
it is done 
![Screenshot (121)](https://github.com/canaris-in/canidesk/assets/103345777/0eb596b9-9a03-4c3e-86f9-ebc275e6866e)

**Comment by lalit510** [comment]
it's working.
