### ISSUE TITLE
Cani desk  > Reports > shadow of background does not display. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#116]
**What's not working **
Cani desk  > Reports > shadow of background does not display. 
![Screenshot 2023-06-21 171221](https://github.com/canaris-in/canidesk/assets/114991909/26d263f7-4acc-4da2-8103-c7848e24c2ed)

**Comment by pravinpimpale** [comment]
it is done 
![Screenshot (123)](https://github.com/canaris-in/canidesk/assets/103345777/a676ae94-2da3-4bbd-9cfa-d0db160473c0)

**Comment by lalit510** [comment]
it's working.
