### ISSUE TITLE
Cani desk > Reports >Settings > not properly display settings panel. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#118]
****What's not working **
Cani desk > Reports >Settings > not properly display settings panel. 
![Screenshot 2023-06-22 133552](https://github.com/canaris-in/canidesk/assets/114991909/b5de2d46-778c-4f26-ae4d-4f797465e2fd)**

**Expected **
show properly and every parts show properly according this screen 
![Screenshot 2023-06-22 133946](https://github.com/canaris-in/canidesk/assets/114991909/0276c8cd-114b-4cc3-a73c-0cb118dbf22c)

**Comment by pravinpimpale** [comment]
it is done by rajesh

**Comment by rajeshcanaris** [comment]
it s done
![Screenshot from 2023-06-20 16-20-46](https://github.com/canaris-in/canidesk/assets/133959091/1a6891dd-fb24-4791-95f6-544bd98a8568)

**Comment by rajeshcanaris** [comment]
it is done
![Screenshot from 2023-06-27 20-50-25](https://github.com/canaris-in/canidesk/assets/133959091/b43124dc-6b5c-4301-992e-d09bda97ba9f)

**Comment by lalit510** [comment]
it's working now.
