### ISSUE TITLE
Create user role

### ISSUE THREAD

**Issue by pravinpimpale** [canaris-in/canidesk#122]
![Screenshot (124)](https://github.com/canaris-in/canidesk/assets/103345777/071c8c48-2c89-4458-be4a-f6405c81160a)
User role
1. Admin
2. ITHead
3. Ticket Coordinator
4. Ticket Engineer

**Comment by lalit510** [comment]
**What's not working **
All bugs mention in Excel sheet.
https://1drv.ms/x/c/6c14608942fbd3b1/EUKLFfYoMHRIujKUiw9W7LwB8_ciqPvpvCg6LH1bQaH_7Q?e=cg6o6v

**Expected ** 
All roles Related requirements 
![Screenshot 2023-06-23 144734](https://github.com/canaris-in/canidesk/assets/114991909/d63a33ca-b233-41b1-9ef8-505f3c6cba4d)

**Comment by lalit510** [comment]
some feedback for roles: 
1. IT Head: users options show in manage section, user click on users option show access denied error.  
![Screenshot 2023-06-23 205651](https://github.com/canaris-in/canidesk/assets/114991909/65f7ce28-1785-4137-a193-400cd587e997)
2. roles issues 
   
![Screenshot 2023-06-23 181047](https://github.com/canaris-in/canidesk/assets/114991909/b2d46e8f-08e5-484a-ae9e-a72f406187c6)

**Comment by lalit510** [comment]
it's working according to this sheet.
[Roles_for_Canidesk (1).xlsx](https://github.com/canaris-in/canidesk/files/11878209/Roles_for_Canidesk.1.xlsx)
