### ISSUE TITLE
Customer portal > Show phone conversations in the customer portal

### ISSUE THREAD

**Issue by umar-ashrfy** [canaris-in/canidesk#126]
![Screenshot 2023-06-23 at 3 31 23 PM](https://github.com/canaris-in/canidesk/assets/13817828/fe2f0c60-e3a3-4c20-94a3-28ec1d81a354)
![Screenshot 2023-06-23 at 3 31 50 PM](https://github.com/canaris-in/canidesk/assets/13817828/d7d615cc-5ab8-4947-aac3-5b7ab8584b9e)

**Comment by rajeshcanaris** [comment]
it is done 
![Screenshot from 2023-06-28 21-53-59](https://github.com/canaris-in/canidesk/assets/133959091/199dc202-a074-4021-b1f9-05157b67721a)
![Screenshot from 2023-06-28 21-53-53](https://github.com/canaris-in/canidesk/assets/133959091/1cf0b8a2-61c3-4fbc-8de1-74bc4705f457)

**Comment by rajeshcanaris** [comment]
phone icon is added
![Uploading Screenshot from 2023-06-28 22-07-53.png…]()

**Comment by rajeshcanaris** [comment]
phone icon is added
![Screenshot from 2023-06-28 22-07-53](https://github.com/canaris-in/canidesk/assets/133959091/01994b7e-8af2-4320-b0a8-afb816374cbb)

**Comment by lalit510** [comment]
it's working now
