### ISSUE TITLE
Customer portal > Change text to Reopen for closed tickets

### ISSUE THREAD

**Issue by umar-ashrfy** [canaris-in/canidesk#129]
![Screenshot 2023-06-23 at 3 48 41 PM](https://github.com/canaris-in/canidesk/assets/13817828/488b3aef-7df4-45bb-8a04-22970e80c4f6)

**Comment by lalit510** [comment]
Reopen button not working. please fix this issue 

https://github.com/canaris-in/canidesk/assets/114991909/68181f2c-6636-4ee4-a627-e1c42da34c70

**Comment by pravinpimpale** [comment]
it is working now

**Comment by lalit510** [comment]
it's working now.
