### ISSUE TITLE
Customer portal > Align buttons as per screenshot and increase size

### ISSUE THREAD

**Issue by umar-ashrfy** [canaris-in/canidesk#130]
![Screenshot 2023-06-23 at 3 47 57 PM](https://github.com/canaris-in/canidesk/assets/13817828/fe38c07d-ef4f-41e6-9b51-67cbc11bf1d5)

**Comment by lalit510** [comment]
it's not working.
![Screenshot 2023-06-26 162657](https://github.com/canaris-in/canidesk/assets/114991909/8748f071-be80-490b-a98e-ce40027f3d88)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (143)](https://github.com/canaris-in/canidesk/assets/103345777/46261672-6c58-4ac4-923d-cc28a2611fe4)

**Comment by lalit510** [comment]
it's working now
