### ISSUE TITLE
Canidesk > Mailbox > Create new tickets > user not able to add image in this ticket

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#133]
**What's not working **
Canidesk > Mailbox > Create new tickets > user not able to add image in this ticket

**Comment by pravinpimpale** [comment]
It is done 
![Screenshot (133)](https://github.com/canaris-in/canidesk/assets/103345777/7330843f-9492-4fd9-a23b-f5d990e87ac9)
![Screenshot (134)](https://github.com/canaris-in/canidesk/assets/103345777/6c956039-5e08-4b58-81a3-a866ea042776)
![Screenshot (135)](https://github.com/canaris-in/canidesk/assets/103345777/3cfa1b79-08f4-4c36-a726-e8891b0e4c3a)

**Comment by lalit510** [comment]
it's not working

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (148)](https://github.com/canaris-in/canidesk/assets/103345777/e2754d4f-8740-4086-bbb7-1c0a9e888827)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (150)](https://github.com/canaris-in/canidesk/assets/103345777/ce803656-2dff-4762-8643-5147ef93c12e)

**Comment by lalit510** [comment]
it's working now
