### ISSUE TITLE
Canidesk > Customers > UI issues show in Customer portal 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#134]
**What's not working **
Canidesk > Customers > UI issues show in Customer portal.
because of user not added name only add email id then create customer id 
![Screenshot 2023-06-23 164109](https://github.com/canaris-in/canidesk/assets/114991909/480864a9-3bba-4fe0-a0be-baa7a8c01e4a)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (136)](https://github.com/canaris-in/canidesk/assets/103345777/8ec26971-eedd-4e65-b650-a36c5f9c52c5)

**Comment by lalit510** [comment]
it's working now
