### ISSUE TITLE
Customer portal > cross icon not working in add customer page. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#135]
**What's not working **
Customer portal > cross icon not working in add customer page. 
![Screenshot 2023-06-23 163658](https://github.com/canaris-in/canidesk/assets/114991909/5757d8b3-8a42-4d97-8f2d-a05d18c10aa0)

**Comment by pravinpimpale** [comment]
It is working

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (146)](https://github.com/canaris-in/canidesk/assets/103345777/5f3ed506-884b-4fa8-ac8a-0e0b4c83bb70)

**Comment by lalit510** [comment]
it's working now
