### ISSUE TITLE
Dashboard > Broken UI if reports module is not activated 

### ISSUE THREAD

**Issue by Shubham40Bears** [canaris-in/canidesk#141]
![Screenshot 2023-06-26 124712](https://github.com/canaris-in/canidesk/assets/84436275/3bf4fb81-dece-43e3-bfdd-fe3d33f8d61d)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (138)](https://github.com/canaris-in/canidesk/assets/103345777/872e56df-995c-48dd-977c-f85adb028263)

**Comment by lalit510** [comment]
it's working now.
