### ISSUE TITLE
Customer panel > icons not proper visible in customer panel 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#148]
**What's not working **
Customer panel > icons not proper visible in customer panel 
![Screenshot 2023-06-27 084526](https://github.com/canaris-in/canidesk/assets/114991909/efca1470-6700-42ce-a413-a3c83182b3a5)

**Comment by lalit510** [comment]
fix this UI
![Screenshot 2023-06-27 085148](https://github.com/canaris-in/canidesk/assets/114991909/ed8337e5-f8d4-49ed-a531-9295901d3568)
 issue

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (144)](https://github.com/canaris-in/canidesk/assets/103345777/4db0043e-5f7b-430a-925f-cdae3b1757c2)
![Screenshot (145)](https://github.com/canaris-in/canidesk/assets/103345777/cfc4354f-73d5-48f2-bb0b-7fc38a545812)

**Comment by lalit510** [comment]
it's working now
