### ISSUE TITLE
Customer panel > user not able to send picture in customer panel.  

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#149]
**What's not working **
Customer panel > user not able to send picture in customer panel.  
![Screenshot 2023-06-27 091900](https://github.com/canaris-in/canidesk/assets/114991909/6bf1d38c-3924-4ae3-b135-49e7373c4231)

**Comment by pravinpimpale** [comment]
it is done

**Comment by pravinpimpale** [comment]
![Screenshot (147)](https://github.com/canaris-in/canidesk/assets/103345777/f311208f-b687-4c84-a362-abd291102e68)

**Comment by pravinpimpale** [comment]
![Screenshot (149)](https://github.com/canaris-in/canidesk/assets/103345777/d0f96108-0de7-476f-b997-c19e854ca987)

**Comment by lalit510** [comment]
it's not working

**Comment by lalit510** [comment]
it's working now
