### ISSUE TITLE
Customer panel > Agent's name is being displayed as Mailbox name.

### ISSUE THREAD

**Issue by umar-ashrfy** [canaris-in/canidesk#153]
What's not working
- Agent name is not displayed.
- Mailbox name is displayed in place of user name.

**Comment by umar-ashrfy** [comment]
![Screenshot 2023-06-27 at 4 50 02 PM](https://github.com/canaris-in/canidesk/assets/13817828/7f441308-7ed0-4450-97a6-f904ae721a1d)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (153)](https://github.com/canaris-in/canidesk/assets/103345777/5430db2d-ddfe-4c5d-a34c-4c2bd35b20c8)

**Comment by lalit510** [comment]
it is not fixed.
![Screenshot 2023-06-29 110320](https://github.com/canaris-in/canidesk/assets/114991909/11f29ea0-aae4-4d12-bc21-d7963627ff6d)

**Comment by rajeshcanaris** [comment]
it is working
![Screenshot from 2023-06-29 22-11-34](https://github.com/canaris-in/canidesk/assets/133959091/1e53f6b4-0a8a-4f2d-b7da-0755dbaab2e0)

**Comment by lalit510** [comment]
it's working now
