### ISSUE TITLE
Cani desk > IT Head create new user > than reset password and delete user options are missing.  

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#156]
**What's not working **
Cani desk > IT Head create new user > than reset password and delete user options are missing.  
![Screenshot 2023-06-28 092732](https://github.com/canaris-in/canidesk/assets/114991909/e2ec7181-5299-47b5-9d65-8c177f12a266)

**Expected **
![Screenshot 2023-06-28 093110](https://github.com/canaris-in/canidesk/assets/114991909/adeef4e5-e015-4eca-a6bb-4ae07ace72e8)

**Comment by pravinpimpale** [comment]
it is done

**Comment by lalit510** [comment]
it's working now.
