### ISSUE TITLE
Cani desk >Manage > Customers > remove any Customer than gap show in customers' page. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#157]
**What's not working **
Cani desk >Manage > Customers > remove any Customer than gap show in customers' page. 
![Screenshot 2023-06-28 104408](https://github.com/canaris-in/canidesk/assets/114991909/cfb95f40-5981-40c1-bb68-eb12bdb54286)

**Comment by pravinpimpale** [comment]
if we write customer name then  not showing this gap

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (154)](https://github.com/canaris-in/canidesk/assets/103345777/d0bd1b57-f28b-492a-a631-42db6fb153c7)

**Comment by lalit510** [comment]
it's not fixed.
![Screenshot 2023-06-28 184259](https://github.com/canaris-in/canidesk/assets/114991909/fa57213c-c194-4aae-9907-2c4537732fd0)

**Comment by pravinpimpale** [comment]
it is done please check now

**Comment by lalit510** [comment]
it's working now
