### ISSUE TITLE
Cani desk > customer panel > Improve UI    

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#165]
![Screenshot 2023-06-29 092414](https://github.com/canaris-in/canidesk/assets/114991909/51ba3bd7-853c-4fdb-b9db-bddc8f449670)

**Comment by lalit510** [comment]
it is normal ticket to improve UI 
like according to screen all tickets list not showing

**Comment by besrabasant** [comment]
@lalit510 How to I access this screen?

**Comment by lalit510** [comment]
box size increase only, not other UI issues  
![Screenshot 2023-06-29 092414](https://github.com/canaris-in/canidesk/assets/114991909/773e39cd-7550-464f-b78d-d76c421c6e16)

**Comment by rajeshcanaris** [comment]
Now it done

**Comment by lalit510** [comment]
it's working now
