### ISSUE TITLE
Cani-desk > full email does not display in customer panel only show subject. (only phone conversation )

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#166]
**What's not working **
Cani-desk > full email does not display in customer panel only show subject. so, customer can't read message. 
![Screenshot 2023-06-29 100327](https://github.com/canaris-in/canidesk/assets/114991909/491d59c0-6202-4d46-b1a8-d93232583c11)

![Screenshot 2023-06-29 100259](https://github.com/canaris-in/canidesk/assets/114991909/3c8ba046-e5e5-42e2-a507-ccaa7d7c1db2)

**Comment by rajeshcanaris** [comment]
it is done

**Comment by lalit510** [comment]
it's working now
