### ISSUE TITLE
Cani-desk > Mailbox > show all tickets count for draft and starred option in mailbox.  

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#168]
**What's not working **
Cani-desk > Mailbox > show all tickets count for draft and starred option in mailbox.  
but only show active tickets count. 
![Screenshot 2023-06-29 115250](https://github.com/canaris-in/canidesk/assets/114991909/808fa58d-ae1d-4bce-b3d9-3ae79b0d02eb)
![Screenshot 2023-06-29 115849](https://github.com/canaris-in/canidesk/assets/114991909/ed6db2ac-bcaa-4189-8529-c178aae6dbde)

**Comment by besrabasant** [comment]
Draft and Starred options in a mailbox should show the total count of the conversations.

**Comment by lalit510** [comment]
According to Basant bhai comment, closed this ticket.
