### ISSUE TITLE
Cani-desk > Dashboard > after select any filter options then all graphs show empty. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#182]
**what's not working **
Cani-desk > Dashboard > after select any filter options then all graphs show empty. 
![Screenshot 2023-07-04 142107](https://github.com/canaris-in/canidesk/assets/114991909/2b153982-eb4e-4732-8514-989589afc0f6)

**Comment by pravinpimpale** [comment]
is is done
![Screenshot (159)](https://github.com/canaris-in/canidesk/assets/103345777/9be71f23-bfd5-4a27-9b5b-d54f6d612544)

**Comment by lalit510** [comment]
it's working now
