### ISSUE TITLE
Cani-desk > Mailbox > In mailbox starred box is empty but it is showing it is not empty.

### ISSUE THREAD

**Issue by rajeshcanaris** [canaris-in/canidesk#197]
Cani-desk > Mailbox > In mailbox starred box is empty but it is showing it is not empty(bug).
![screenshot__6_](https://github.com/canaris-in/canidesk/assets/133959091/f25454e3-ef6c-4a8c-820b-db9494c6cc4a)

**Comment by lalit510** [comment]
it's working in demo
