### ISSUE TITLE
Cani-desk > custom fields are not display in customer panel after active by the admin.   

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#212]
**What's not working **
Cani-desk > custom fields are not display in customer panel after active by the admin.   
![Screenshot 2023-07-24 120848](https://github.com/canaris-in/canidesk/assets/114991909/9dad0a77-6c95-4bf3-a166-22a9f75bb53e)

**Comment by rajeshcanaris** [comment]
![Screenshot from 2023-07-24 23-45-15](https://github.com/canaris-in/canidesk/assets/133959091/c3c697ed-3791-4d02-9b5c-37ecfeb4d132)
you need to click this checkbox and save 
![Screenshot from 2023-07-24 23-46-33](https://github.com/canaris-in/canidesk/assets/133959091/e7aaa982-9785-468a-9380-722b693964f1)

**Comment by lalit510** [comment]
it's working now
