### ISSUE TITLE
Cani-desk > Mailbox > error display / mail not properly fetch in mailbox when user open tickets.

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#217]
**What's not working **
Cani-desk > Mailbox > error display in mailbox when user open tickets.
![Screenshot 2023-07-24 at 3 09 51 PM](https://github.com/canaris-in/canidesk/assets/114991909/ccbeb897-68cf-4ba1-beb4-86cdc7786ca3)

**Comment by pravinpimpale** [comment]
it is done

**Comment by m-omkar** [comment]
![Screenshot 2023-07-26 110253](https://github.com/canaris-in/canidesk/assets/140042003/ae5afc7f-966e-4c49-9982-85a7ab61157f)
It's Working.
