### ISSUE TITLE
CaniDesk > Dashboard > Unassigned tickets count show wrong  

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#45]
**What's not working **
CaniDesk > Dashboard > Unassigned tickets count show wrong  
![Screenshot 2023-06-05 164326](https://github.com/canaris-in/canidesk/assets/114991909/706ed97b-7540-4e20-91e5-c4f4e5c134ac)

**Expected **
All types tickets count properly show

**Comment by pravinpimpale** [comment]
Unassigned tickets count show fixed but accourding databases table if we deleted any ticket using application but this ticket not delete from databases

**Comment by lalit510** [comment]
**what's not working **
1. All tickets in mine section show in Unassigned tickets in dashboard.
 but these tickets assign already admin/ 
![Screenshot 2023-06-27 142844](https://github.com/canaris-in/canidesk/assets/114991909/2cae0182-4d26-4e65-8c53-26db586f02fe)

**Comment by lalit510** [comment]
it's not working properly

**Comment by lalit510** [comment]
it's working now
