### ISSUE TITLE
Canidesk > new user not able to login and show error 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#47]
**What's not working**
Canidesk > new user not able to login and show error.
![Screenshot 2023-06-07 135125](https://github.com/canaris-in/canidesk/assets/114991909/0f4caa21-667d-4673-ae54-09df2d0d2e46)

**Expected ** 
new user should be properly login.

**Comment by Shubham40Bears** [comment]
Blocker: Cannot debug after creating User role, creating other ticket for this bug

**Comment by lalit510** [comment]
it's working now.
