### ISSUE TITLE
Canidesk >after mobile mode (responsive testing)> all options of main tabs should not be visible properly when dark mode is on 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#49]
**What's not working**
Canidesk >after mobile mode (responsive testing)> all options of main tabs should not be visible properly. 
![Screenshot 2023-06-08 153542](https://github.com/canaris-in/canidesk/assets/114991909/085a7924-d560-4fa3-bb50-3664d0a49eb6)

**Expected **
all options / dropdown should be proper visible.

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (73)](https://github.com/canaris-in/canidesk/assets/103345777/4dc30b0f-78e5-4a36-bf21-1cf99ac43e91)

**Comment by lalit510** [comment]
it's working
