### ISSUE TITLE
Canidesk > Mailbox > Responsive testing > mailbox name not visible properly when dark mode ONA

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#50]
**What's not working **
Canidesk > Mailbox > Responsive testing > mailbox name not visible properly when dark mode ONA
![Screenshot 2023-06-08 160554](https://github.com/canaris-in/canidesk/assets/114991909/dab4200b-fd95-40bd-afcb-39ffb22422a4)

**Expected **
name should be visible.

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (71)](https://github.com/canaris-in/canidesk/assets/103345777/0f0477ae-b9bd-4a7d-a92d-4da3b261aa8e)

**Comment by lalit510** [comment]
it's working
