### ISSUE TITLE
Canidesk > Manage > logs > all details not visible when dark mode is ON 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#51]
**What's not working **
Canidesk > Manage > logs > all details not visible when dark mode is ON 
select any options like outgoing Emails, Fetch Errors all options in logs tab. 
![Screenshot 2023-06-08 163332](https://github.com/canaris-in/canidesk/assets/114991909/38045e97-ee31-41a1-b289-b78899de3496)
![Screenshot 2023-06-08 163356](https://github.com/canaris-in/canidesk/assets/114991909/f4781df1-5cfc-4541-8d9a-fd2901bda8ae)

**Expected**
All details should be visible.
![Screenshot 2023-06-08 164504](https://github.com/canaris-in/canidesk/assets/114991909/4d768c5a-b184-4398-b5df-b1ee0e23938f)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (67)](https://github.com/canaris-in/canidesk/assets/103345777/ac0bac30-22db-47fe-8649-77f8b465557a)

**Comment by lalit510** [comment]
Manage > Logs > App logs > search icon not visible properly 
![Screenshot 2023-06-21 101220](https://github.com/canaris-in/canidesk/assets/114991909/a57f90cc-118f-4b78-aa9c-8faec679d14f)

**Comment by pravinpimpale** [comment]
it is done
![Uploading Screenshot (122).png…]()

**Comment by pravinpimpale** [comment]
![Screenshot (122)](https://github.com/canaris-in/canidesk/assets/103345777/821264ab-a928-42cd-8fe5-c4e2808810cd)

**Comment by lalit510** [comment]
it's working
