### ISSUE TITLE
Canidek > Manage > hide "Translate " module. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#52]
**What's not working **
Canidek > Manage > hide "Translate " module. 
![Screenshot 2023-06-09 125718](https://github.com/canaris-in/canidesk/assets/114991909/e4e77b62-28cb-48e0-a33e-5f8b94f6c703)

**Comment by pravinpimpale** [comment]
it is done

**Comment by lalit510** [comment]
fixed the issue
