### ISSUE TITLE
Canidesk > All filter not working properly together in dashboard. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#57]
**What's not working **
Cani desk > All filter not working together in dashboard.

**Comment by pravinpimpale** [comment]
![Screenshot (76)](https://github.com/canaris-in/canidesk/assets/103345777/ba6f0d79-ed92-44f4-9d7d-fb5a92c7b5da)

**Comment by lalit510** [comment]
Tickets count not properly show.  
![Screenshot 2023-06-27 133046](https://github.com/canaris-in/canidesk/assets/114991909/bebdf6dc-6383-4584-ba08-68a615ef9128)
![Screenshot 2023-06-27 133108](https://github.com/canaris-in/canidesk/assets/114991909/175af3d5-5082-4fbb-b15c-be3b435c6d89)

**Comment by lalit510** [comment]
**What's not working **
ticket categories filter :
for canaris support mailbox  
1. select All than tickets count show 7522 
![Screenshot 2023-06-29 114602](https://github.com/canaris-in/canidesk/assets/114991909/afcc9904-0339-4d59-bf2c-0b921d2604a2)
2. select other categories but ticket count does not match properly 
 all and other categories count does not equal.

**Comment by lalit510** [comment]
it's close after some discussion with Umar sir
