### ISSUE TITLE
Cani-desk > Reports > SLA REPORT > please change according to design. (Add download button with drop-down)

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#60]
**What's not working **
Cani-desk > Reports > SLA REPORT > please change according to design. (Add download button with drop-down)
demo design:
![Screenshot 2023-06-15 115147](https://github.com/canaris-in/canidesk/assets/114991909/bf0da135-1a94-400b-8ab1-bb6cc86f142b)

**Expected ** 
according to design please add download button
![Screenshot 2023-06-15 113150](https://github.com/canaris-in/canidesk/assets/114991909/90e84d02-30e0-4ebc-8d3c-af25d2ac8f5d)

**Comment by pravinpimpale** [comment]
download button added
