### ISSUE TITLE
Cani-desk > Manage > users > all users names do not display properly when dark mode is ON 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#61]
**What's not working **Cani-desk > Manage > users > all users names do not display properly when dark mode is ON 
![Screenshot 2023-06-15 153837](https://github.com/canaris-in/canidesk/assets/114991909/8990f93f-933a-47d7-b9f8-68517a19d92e)

**Expected **
all users name should be proper display

**Comment by pravinpimpale** [comment]
It is done

**Comment by lalit510** [comment]
avatar name of user not properly 
![Screenshot 2023-06-19 152631](https://github.com/canaris-in/canidesk/assets/114991909/60757b1c-5de8-44c0-a2fc-8d3fc325987e)

**Comment by pravinpimpale** [comment]
It is done 
![Screenshot (104)](https://github.com/canaris-in/canidesk/assets/103345777/edf9d30f-dbf3-417b-9696-9978039e88fd)

**Comment by lalit510** [comment]
it's working.
