### ISSUE TITLE
Canidesk > Manage > Users > users not properly display and tags not proper added 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#62]
**what's not working **
Canidesk > Manage > Users > users not properly display and tags not proper added 
users not properly display 
users tag like admin;
![Screenshot 2023-06-15 154439](https://github.com/canaris-in/canidesk/assets/114991909/c7b8fbd4-bd08-477d-8ddb-00e2fdae5dbc)
 not invited and invited tags not properly show.

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (64)](https://github.com/canaris-in/canidesk/assets/103345777/2eca01fa-3f23-4d7e-9c96-fbae0a6e44e7)

**Comment by lalit510** [comment]
fix this issue 
![Screenshot 2023-06-17 162750](https://github.com/canaris-in/canidesk/assets/114991909/b347a2ef-6ebe-4d41-93d5-c315ad4d1483)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (104)](https://github.com/canaris-in/canidesk/assets/103345777/d9a54d00-429c-4f8c-aa4b-13b6e42c6ab9)

**Comment by lalit510** [comment]
it's working
