### ISSUE TITLE
Canidesk > product > please remove "none of the above " option in the filter. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#68]
**What's not working **
Canidesk > product > please remove "none of the above " option in the filter. 
![Screenshot 2023-06-16 093844](https://github.com/canaris-in/canidesk/assets/114991909/f451b7e6-8584-4fd0-bd25-3430966ce7b3)

**Comment by pravinpimpale** [comment]
it is done

**Comment by lalit510** [comment]
not reflected now please check again

**Comment by pravinpimpale** [comment]
For that need to migrate the data

**Comment by pravinpimpale** [comment]
i have changed the migration file

**Comment by lalit510** [comment]
it's not fixed now

**Comment by lalit510** [comment]
it's not reflected now

**Comment by lalit510** [comment]
it's working now
