### ISSUE TITLE
Cani-desk > Reports > without select filter show tickets reports. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#69]
**What's not working **
Cani-desk > Reports > without select filter show tickets reports. 
![Uploading Screenshot 2023-06-16 102825.png…]()

**Comment by lalit510** [comment]
it's not working.

**Comment by pravinpimpale** [comment]
can you please attach screenshot

**Comment by lalit510** [comment]
all filters are empty and data display. Please
![Screenshot 2023-06-21 114538](https://github.com/canaris-in/canidesk/assets/114991909/09486703-a470-4cbf-978f-45a9b2db9525)
 fix this.

**Comment by lalit510** [comment]
![Screenshot 2023-06-21 114701](https://github.com/canaris-in/canidesk/assets/114991909/02af2b88-377a-4cbd-bc71-613fd81b1e16)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (118)](https://github.com/canaris-in/canidesk/assets/103345777/1c30d9fa-9a0a-4eb1-ae32-33191eadea2d)
![Screenshot (119)](https://github.com/canaris-in/canidesk/assets/103345777/8df33f9e-0827-4e23-828f-eefd8fb8730b)

**Comment by lalit510** [comment]
it's working now
