### ISSUE TITLE
Cani desk > Mailbox > count of closed tickets does not display in mailbox page. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#71]
**What's not working **
Cani desk > Mailbox > count of closed tickets does not display in mailbox page. 
![Screenshot 2023-06-16 112139](https://github.com/canaris-in/canidesk/assets/114991909/1463eb45-df93-4ea2-b2b9-f5bcfcb8d4db)

**Comment by besrabasant** [comment]
The count of closed tickets should not be displayed on the mailbox page. Please close this ticket.

**Comment by lalit510** [comment]
closed tickets
