### ISSUE TITLE
Canidesk > dashboard > Calendar icon does not display properly in date fields when dark mode is ON 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#72]
**What's not working **
Cani desk > dashboard > Calendar icon does not display properly in date fields when dark mode is ON 
![Screenshot 2023-06-17 090138](https://github.com/canaris-in/canidesk/assets/114991909/82d8afc7-64a5-417e-b4bd-53035466eec8)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (113)](https://github.com/canaris-in/canidesk/assets/103345777/9a389a54-c49e-4d6f-959d-5e4690b49fa4)

**Comment by lalit510** [comment]
it's working
