### ISSUE TITLE
Cani-desk > Reports > SLA Reports > click on download icon then background color change.  

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#73]
**What's not working **
Cani-desk > Reports > SLA Reports > click on download icon then background color change.  but only show dropdown options 

https://github.com/canaris-in/canidesk/assets/114991909/797ca2ce-4923-4052-91c3-3486669489a9

**Comment by pravinpimpale** [comment]
this is fixed

**Comment by lalit510** [comment]
this issue fixed.

**Comment by lalit510** [comment]
closed
