### ISSUE TITLE
Cani desk > Reports > Tickets report > all filters are not display.

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#74]
**What's not working**
Cani desk > Reports > Tickets report > all filters are not display.
![Screenshot 2023-06-17 101654](https://github.com/canaris-in/canidesk/assets/114991909/6c446ebf-c018-4121-a7af-68041569e7cd)

**Expected **
all filters display in tickets report.

**Comment by pravinpimpale** [comment]
![Screenshot (69)](https://github.com/canaris-in/canidesk/assets/103345777/e72e4088-9500-4cf8-a5e8-7dcb60867753)

**Comment by lalit510** [comment]
please fix this issue

**Comment by pravinpimpale** [comment]
It is done 
you need to install custome field module

**Comment by lalit510** [comment]
again show error

**Comment by lalit510** [comment]
it's working
