### ISSUE TITLE
Cani-desk > Reports > tickets report > according to Figma design change it 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#75]
**What's not working **
Cani-desk > Reports > tickets report > according to Figma design change it 
![Screenshot 2023-06-17 101654](https://github.com/canaris-in/canidesk/assets/114991909/3c259c9e-e6b3-457c-8a76-4955d103ff98)

**Expected **
change according to design.
![Screenshot 2023-06-17 103010](https://github.com/canaris-in/canidesk/assets/114991909/5a4b9ffa-caa8-49b6-969c-e9f503a0eaa4)

**Comment by pravinpimpale** [comment]
Dont need to develop

**Comment by Shubham40Bears** [comment]
As per discussion with @pravinpimpale and @umar-ashrfy sir no changes needed. Closing this issue.
