### ISSUE TITLE
Cani-desk > Mailbox >open any tickets > click on more action icon then select merge option > background color change automatically  

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#78]
**What's not working **
Cani-desk > Mailbox >open any tickets > click on more action icon then select merge option > background color change automatically.

https://github.com/canaris-in/canidesk/assets/114991909/0ed0db29-5785-4996-b37b-6ccc0b4ff53b

**Comment by pravinpimpale** [comment]
It is done 
![Screenshot (89)](https://github.com/canaris-in/canidesk/assets/103345777/8db6ac4f-7227-4e5b-a852-8b2ec2bcfb38)
![Screenshot (90)](https://github.com/canaris-in/canidesk/assets/103345777/8a35c81c-a4b4-4d55-812d-00b7b925bf3b)

**Comment by lalit510** [comment]
this issue is not resolved.

**Comment by pravinpimpale** [comment]
It is done please check

**Comment by lalit510** [comment]
it's working properly.
