### ISSUE TITLE
Cani-desk > Mailbox > select any ticket. > select merge action > warning message show white. dark mode is on 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#79]
**What's not working **
Cani-desk > Mailbox > select any ticket. > select merge action > warning message show white. 
![Screenshot 2023-06-17 145327](https://github.com/canaris-in/canidesk/assets/114991909/3b97a6fa-12e6-4884-aec3-9a0f36657ead)

**Comment by pravinpimpale** [comment]
It is done 
![Screenshot (80)](https://github.com/canaris-in/canidesk/assets/103345777/f2ecda5a-3aa1-441d-b811-0db7bd804c05)

**Comment by lalit510** [comment]
in light mode 
warning message does not display and background color change.

https://github.com/canaris-in/canidesk/assets/114991909/93e66463-8a27-4547-828a-4bd70ad5b56c

**Comment by pravinpimpale** [comment]
It is fixed
![Screenshot (99)](https://github.com/canaris-in/canidesk/assets/103345777/38260074-5375-4533-b72c-dab46b9b5ee8)

**Comment by lalit510** [comment]
it's fixed
