### ISSUE TITLE
Cani-desk > dashboard > responsive testing > click on filter icon than back text display properly when dark mode is ON 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#80]
**What's not working **
Cani-desk > dashboard > responsive testing > click on filter icon than back text display properly when dark mode is ON 
![Screenshot 2023-06-17 150220](https://github.com/canaris-in/canidesk/assets/114991909/fbf3d595-845a-4ee2-aa6a-1c0ba4cb2755)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (79)](https://github.com/canaris-in/canidesk/assets/103345777/f8853d32-180e-48de-a1fd-0a147d1d2eed)

**Comment by lalit510** [comment]
it's working properly
