### ISSUE TITLE
Cani desk > Reports > responsive testing > SLA Reports > download icon displays over search field. and drop-down show left side 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#81]
**What's not working **
Cani desk > Reports > responsive testing > SLA Reports > download icon displays over search field. and drop-down show left side 
![Screenshot 2023-06-17 151950](https://github.com/canaris-in/canidesk/assets/114991909/72e7cfbb-16d9-4ed1-9a7d-7ebb54593ae7)
![Screenshot 2023-06-17 151906](https://github.com/canaris-in/canidesk/assets/114991909/32434854-6972-4197-aaac-a7c44cf60fb2)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (78)](https://github.com/canaris-in/canidesk/assets/103345777/1d1a994b-e81c-446a-b7b5-95abd12c0de6)

**Comment by lalit510** [comment]
it's completed now
