### ISSUE TITLE
Cani-desk > Dashboard > please change color according to design. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#83]
**What's not working **
Cani-desk > Dashboard > please change color according to design. 
![Screenshot 2023-06-19 093849](https://github.com/canaris-in/canidesk/assets/114991909/abe4ef24-beb0-455c-b6fc-2cfdbfadeb35)

**Expected **
please change according to this design 
![Screenshot 2023-06-19 094159](https://github.com/canaris-in/canidesk/assets/114991909/ece0f6ea-8b20-4c41-8f26-294b8dc108b0)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (85)](https://github.com/canaris-in/canidesk/assets/103345777/153b6565-b6a3-4b1a-8d4b-3a517869ee73)

**Comment by lalit510** [comment]
done
