### ISSUE TITLE
Cani-desk > create ticket in Drafts > Drafts tickets do not show in SLA report. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#85]
**What's not working **
Cani-desk > create ticket in Drafts > Drafts tickets do not show in SLA report. 
![Screenshot 2023-06-19 095317](https://github.com/canaris-in/canidesk/assets/114991909/a5a63fa6-86bc-44fc-9799-f2faced6f766)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (92)](https://github.com/canaris-in/canidesk/assets/103345777/1982cc44-2b61-47bb-86e4-4e1533af48c0)
![Screenshot (93)](https://github.com/canaris-in/canidesk/assets/103345777/654618b3-ffb6-4128-8aae-ca17730c9009)

**Comment by lalit510** [comment]
it's working now
