### ISSUE TITLE
Cani-desk > Dashboard > toggle button of mode only shows dark mode and after change does not disappear. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#86]
**What's not working **
Cani-desk > Dashboard > toggle button of mode only shows dark mode and after change does not disappear. 
![Screenshot 2023-06-19 102532](https://github.com/canaris-in/canidesk/assets/114991909/82b35027-bd82-432e-b801-bae1bd599007)
![Screenshot 2023-06-19 102739](https://github.com/canaris-in/canidesk/assets/114991909/5f1f2e08-07ec-43f1-b4ea-d9855d8ef68b)

**Comment by pravinpimpale** [comment]
Shubham Sir told no need for now

**Comment by pravinpimpale** [comment]
please close this ticket

**Comment by lalit510** [comment]
close this issue
