### ISSUE TITLE
Cani-desk > Dashboard > please change this text color in dark mode. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#89]
**What's not working**
 Cani-desk > Dashboard > please change this text color in dark mode. 
![Screenshot 2023-06-19 133558](https://github.com/canaris-in/canidesk/assets/114991909/fd4f9b92-72de-4a29-b4fb-9fe16a176fd8)

**Comment by pravinpimpale** [comment]
it is done
![Screenshot (88)](https://github.com/canaris-in/canidesk/assets/103345777/9ea78e77-1dfb-497a-93a4-c93841088fd8)

**Comment by lalit510** [comment]
it's fixed now
