### ISSUE TITLE
Cani-desk > knowledge -Base  > go to settings option than its color change white to blue fix this. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#90]
**What's not working **
Cani-desk > knowledge -Base  > go to settings option than its color change white to blue fix this. 
![Screenshot 2023-06-19 154206](https://github.com/canaris-in/canidesk/assets/114991909/2aefe098-515f-4c43-919d-5f642ff65971)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (98)](https://github.com/canaris-in/canidesk/assets/103345777/805b50a0-ef54-4603-b951-c21879cd1248)

**Comment by lalit510** [comment]
it's working now
