### ISSUE TITLE
Mailbox > Add button to fetch latest email for current mailbox

### ISSUE THREAD

**Issue by umar-ashrfy** [canaris-in/canidesk#91]
What's expected
1. User open the mailbox
2. User clicks on the Fetch mail button (refresh icon)
3. Button gets disabled and show loading. https://stackoverflow.com/a/26228354/2225315
4. Latest image gets fetched and loading gets stopped.
5. If any error happens, show the error as message.

![fetch-email](https://github.com/canaris-in/canidesk/assets/13817828/93132d07-695a-4d8b-9ccd-c43b9312b9cb)

**Comment by lalit510** [comment]
it's working now

**Comment by lalit510** [comment]
after error show than which message display in screen

**Comment by pravinpimpale** [comment]
it is done

**Comment by pravinpimpale** [comment]
![Screenshot (158)](https://github.com/canaris-in/canidesk/assets/103345777/a405dd9f-91ef-43f0-b8d4-c1563d3b73f2)

**Comment by lalit510** [comment]
it's working now.
