### ISSUE TITLE
Cani-desk > Mailbox > open any tickets > more action context menu. > close icon not properly display in move & merge option 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#92]
**What's not working **
Cani-desk > Mailbox > open any tickets > more action context menu. > close icon not properly display in move & merge option 
![Screenshot 2023-06-19 164604](https://github.com/canaris-in/canidesk/assets/114991909/10b1e94f-425f-4be6-adfc-3d37f5ac4d18)

**Comment by pravinpimpale** [comment]
It is done 
![Screenshot (103)](https://github.com/canaris-in/canidesk/assets/103345777/8ed4eef6-6fdd-4047-9d9c-33e6ffbcd099)

**Comment by lalit510** [comment]
it's display properly
