### ISSUE TITLE
Cani-desk> Manage > Customers> logo of customers shows white. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#94]
**What's not working **
Cani-desk> Manage > Customers> logo of customers shows white. 
![Screenshot 2023-06-19 173753](https://github.com/canaris-in/canidesk/assets/114991909/baf81734-8eda-415c-80fa-23ced6176e5a)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (112)](https://github.com/canaris-in/canidesk/assets/103345777/128d2aed-4a58-41a0-a046-524ddeca64f6)

**Comment by lalit510** [comment]
show's properly
