### ISSUE TITLE
Cani-desk > Mailbox > open any ticket. > color of mail display wrong in mailbox 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#95]
**What's not working **
Cani-desk > Mailbox > open any ticket. > color of mail display wrong in mailbox 
![Screenshot 2023-06-19 174536](https://github.com/canaris-in/canidesk/assets/114991909/fc4e8283-e894-4571-93e0-097af9b8682f)

**Comment by pravinpimpale** [comment]
It is done please check

**Comment by lalit510** [comment]
it's not reflected 
![Screenshot 2023-06-21 111523](https://github.com/canaris-in/canidesk/assets/114991909/8d1652d4-0c4f-459e-8133-356468fa186c)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (117)](https://github.com/canaris-in/canidesk/assets/103345777/df28c904-c030-43e3-a352-f35b81dacab8)

**Comment by lalit510** [comment]
it's fixed now
