### ISSUE TITLE
Cani-desk > login page > please change color of forget password text..

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#97]
**What's not working **
Cani-desk > login page > please change color of forget password text..
![Screenshot 2023-06-20 085840](https://github.com/canaris-in/canidesk/assets/114991909/ea811d1d-cd00-4808-9d50-ac8df3948a00)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (107)](https://github.com/canaris-in/canidesk/assets/103345777/c4a8b88f-9627-44a6-a7c6-f1eb51893773)

**Comment by lalit510** [comment]
not reflected

**Comment by pravinpimpale** [comment]
Changes reflected please check

**Comment by lalit510** [comment]
it's working now
