### ISSUE TITLE
Canidesk > mailbox > more action > text field does not display properly. 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#98]
**What's not working **
Canidesk > mailbox > more action > text field does not display properly. 
![Screenshot 2023-06-20 091542](https://github.com/canaris-in/canidesk/assets/114991909/bc7c4612-4ca6-4331-8012-d3a3a92e73dc)
![Screenshot 2023-06-20 091635](https://github.com/canaris-in/canidesk/assets/114991909/922eacd7-49f0-47e0-8bd2-7af2b93dcc09)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (106)](https://github.com/canaris-in/canidesk/assets/103345777/99d9c787-1da9-4f41-b513-9e173decc147)

**Comment by lalit510** [comment]
it's working
