### ISSUE TITLE
Cani-desk > Mailbox > open new ticket > avatar is not display properly 

### ISSUE THREAD

**Issue by lalit510** [canaris-in/canidesk#99]
**What's not working **
Cani-desk > Mailbox > open new ticket > avatar is not display properly 
![Screenshot 2023-06-20 092632](https://github.com/canaris-in/canidesk/assets/114991909/4abd6643-0da0-4288-8bea-19c3d64050b7)

**Comment by pravinpimpale** [comment]
It is done
![Screenshot (108)](https://github.com/canaris-in/canidesk/assets/103345777/bf084d41-f956-4864-a237-b748404ca7cb)

**Comment by pravinpimpale** [comment]
![Screenshot (111)](https://github.com/canaris-in/canidesk/assets/103345777/ffd0c9f3-cc56-4df4-a802-c703a62ae351)

**Comment by lalit510** [comment]
it's working
